FROM debian:bullseye
RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev libssl-dev build-essential vim
RUN apt-get install -y sudo git python3 python3-distro
RUN apt-get install gnupg2 wget
RUN wget -qO - https://packages.irods.org/irods-signing-key.asc | sudo apt-key add - &&\
    echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods.list
# apt-get update --allow-insecure-repositories
RUN apt-get update --allow-unauthenticated
RUN apt-get install -y irods-externals-*
RUN apt-get install -y irods-dev
WORKDIR /opt
# https://github.com/irods/externals?tab=readme-ov-file#rhel--centos-7
RUN git clone https://github.com/irods/externals.git &&\
    cd externals &&\
    ./install_prerequisites.py &&\
    make

COPY . /hydroshare-quota
# vim CMakeLists.txt. # edit 4.3.1
RUN /opt/irods-externals/cmake3.21.4-0/bin/cmake .
RUN mkdir -p DEBAIN && touch DEBIAN/control
# RUN cat <<EOT >> DEBIAN/control \
#     Package: hydroshare-quota \
#     Version: 999 \
#     Maintainer: CUAHSI \
#     Architecture: all \
#     Description: hydroshare-quota \
#     EOT
SHELL ["/bin/bash", "-c"]
RUN echo $'Package: hydroshare-quota \n\
Version: 999 \n\
Maintainer: CUAHSI \n\
Architecture: all \n\
Description: hydroshare-quota' > DEBIAN/control

WORKDIR /hydroshare-quota
RUN dpkg-deb --build hydroshare-quota

# for local development:
# docker cp hydroshare-quota.deb data.local.org:/root/
# cat <<EOF | docker exec --interactive data.local.org sh
# dpkg -i /root/hydroshare-quota.deb
# chmod -R 775 /etc/irods
# EOF