name: Test build

on: push

jobs:
  build:
    name: Setup, Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
        max-parallel: 6
        # select a core set of images to build
        matrix:
          IMAGE_VARIANT:
            - Dockerfile
            - Dockerfile-deb
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build
        run: |
          docker build -f ${{ matrix.IMAGE_VARIANT }} .