name: Periodically Build

on:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 every Sunday

  workflow_dispatch:

jobs:
  setup-build:
    name: Setup, Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 6
      # select a core set of images to build
      matrix:
        IMAGE_VARIANT:
          - Dockerfile
          - Dockerfile-deb
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ github.event.action }} != 'workflow_dispatch'
      
      - name: Checkout, ref = ${{ github.ref_name }}
        uses: actions/checkout@v2
        if: ${{ github.event.action }} == 'workflow_dispatch'
        with:
          ref: ${{ github.ref_name }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.IMAGE_VARIANT }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # Archive the built package
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-artifacts
          path: |
            /*.rpm
            /*.deb
